'use client';

import { Canvas, useFrame } from '@react-three/fiber';
import { Environment, Float, MeshTransmissionMaterial, Sparkles } from '@react-three/drei';
import { EffectComposer, Bloom } from '@react-three/postprocessing';
import { useEffect, useRef, useState } from 'react';
import * as THREE from 'three';

function Core(){const ref=useRef<THREE.Mesh>(null);useFrame((state)=>{if(!ref.current)return;ref.current.rotation.x=state.clock.elapsedTime*.08;ref.current.rotation.y=state.clock.elapsedTime*.12;ref.current.position.x=THREE.MathUtils.lerp(ref.current.position.x,state.pointer.x*.16,.025);ref.current.position.y=THREE.MathUtils.lerp(ref.current.position.y,state.pointer.y*.1,.025)});return <Float speed={1.1} rotationIntensity={.2} floatIntensity={.24}><mesh ref={ref}><icosahedronGeometry args={[1.15,4]}/><MeshTransmissionMaterial color="#d9ff8c" transmission={.86} thickness={1.1} roughness={.12} ior={1.45} chromaticAberration={.025} anisotropy={.1}/></mesh><mesh scale={1.12} rotation={[.3,.2,0]}><icosahedronGeometry args={[1.15,2]}/><meshBasicMaterial color="#eaffc2" wireframe transparent opacity={.14}/></mesh></Float>}

function Rings(){const a=useRef<THREE.Group>(null);useFrame((_,delta)=>{if(a.current)a.current.rotation.z+=delta*.04});return <group ref={a}><mesh rotation={[Math.PI*.5,.3,.1]}><torusGeometry args={[1.65,.008,8,160]}/><meshBasicMaterial color="#d9ff8c" transparent opacity={.4}/></mesh><mesh rotation={[.7,0,.8]}><torusGeometry args={[1.95,.006,8,160]}/><meshBasicMaterial color="#b8e99a" transparent opacity={.22}/></mesh></group>}

export default function StudioCanvas(){const [mobile,setMobile]=useState(false);const [reduced,setReduced]=useState(false);useEffect(()=>{const mobileQuery=matchMedia('(max-width: 767px)');const motionQuery=matchMedia('(prefers-reduced-motion: reduce)');const sync=()=>{setMobile(mobileQuery.matches);setReduced(motionQuery.matches)};sync();mobileQuery.addEventListener('change',sync);motionQuery.addEventListener('change',sync);return()=>{mobileQuery.removeEventListener('change',sync);motionQuery.removeEventListener('change',sync)}},[]);if(reduced)return <div className="hero-canvas-fallback" aria-hidden="true"/>;const particles=mobile?180:520;return <div className="hero-canvas" aria-hidden="true"><Canvas dpr={mobile?[1,1.15]:[1,1.5]} camera={{position:[0,0,5.8],fov:35}} gl={{antialias:!mobile,powerPreference:'high-performance'}}><color attach="background" args={['#050505']}/><Environment preset="studio"/><ambientLight intensity={.3}/><pointLight position={[2,2,3]} intensity={mobile?4:7} color="#d9ff8c"/><Core/><Rings/><Sparkles count={particles} scale={[5,3.4,3]} size={mobile?1.1:1.4} speed={.15} color="#d9ff8c" opacity={mobile?.2:.26}/>{!mobile&&<EffectComposer multisampling={0}><Bloom intensity={.4} luminanceThreshold={.72} mipmapBlur/></EffectComposer>}</Canvas></div>}
